<#include "/parts/security.ftlh">
<#import "/parts/common.ftlh" as c>

<@c.page>

<div class="row">
    <div class="col-md-12 error-container">
        <div class="error-code">500</div>
        <div class="error-message">Oops! Something went wrong. Try again later</div>
        <p class="mt-4">We are notified about the problem and already working on it.</p>
        <a href="/" class="btn btn-primary return-home-btn">Return to Home</a>
    </div>
</div>

</@c.page>