<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome to Bookstore</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <header>
        <div class="container">
            <div id="branding">
                <h1><span class="highlight">Book</span>store</h1>
            </div>
             <nav>
                <#include "menu.ftlh">
             </nav>
        </div>
    </header>
    <div class="showcase">
        <div class="container">
            <h1>Welcome to Bookstore</h1>
            <p>Discover a wide selection of books for all tastes and interests.</p>
            <a href="#" class="btn">Explore Now</a>
        </div>
    </div>
</body>
</html>
