<#include "security.ftlh">

  <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
            <a class="navbar-brand text-white custom-font">LETTER <img src="/book.jpeg" class="mr-2" width="30" height="30"></a>
            <div class="login-register">
                <a href="#" class="text-white">Login</a> | <a href="#" class="text-white">Logout</a><br>
                <a href="#" class="text-white">Register</a>
            </div>
        </div>
    </nav>